name: LittleBrother
version: 1.0-alpha
author: Pyramid
main: com.Pyramid.LittleBrother.LittleBrother

permissions:
  LittleBrother.lb:
    default: op

commands:
   LittleBrother:
      description: Commands of LittleBrother.
      usage: /lb для помощи
      aliases: [lb]
      permission: LittleBrother.lb
      permission-message: У вас не достаточно <прав>
